queue:
  name: Example Pipeline Test

trigger:
- master
#- develop
#- features/*
#- hotfix/*
#- release/*

steps:

- task: UsePythonVersion@0
  displayName: 'Use Python 3.x'

- bash: |
   pip install pytest 
   pip install pytest-cov 
   pip install pytest-xdist 
  # pip install pytest-bdd 

  displayName: 'Install a bunch of pip packages.'
- bash: 'pytest -v test/test_accum.py' 
  #workingDirectory: '010_CrackingCodeBasic'
  displayName: 'Run test 010'

- task: PublishTestResults@2
  displayName: 'Publish test result /010.xml'
  inputs:
    testResultsFiles: '$(Build.StagingDirectory)/010.xml'
    testRunTitle: 010
