# Definir los pasos de la tubería
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    python3 -m venv env
    source env/bin/activate
    python3 -m pip install --upgrade pip
# pip install -r requirements.txt
  displayName: 'Configurar el entorno virtual e instalar dependencias'

- script: |
    pytest test/test_accum.py
  displayName: 'Ejecutar pruebas'

# Opcionalmente, añade un paso para publicar los resultados de las pruebas
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results.xml'
    testRunTitle: 'Pruebas automatizadas de mi aplicación'
  condition: succeededOrFailed()
  displayName: 'Publicar resultados de pruebas'
